PLIP 9327: unified interface for lists of content
=================================================

PLIP ticket: http://dev.plone.org/plone/ticket/9327

Review by Craig Haynal (cah190@psu.edu, cah190 on irc)

The PLIP was reviewed on Mac OS X 10.6.5 using python 2.6.6 and Camino
2.0.6.


Review steps
------------

- Ran the plip9327-contentlisting.cfg buildout.

- Ran tests for plone.app.contentlisting.

- Ran alltests.

- Created and examined a new Plone site to look for any obvious issues.

- Examined code.


Notes and observations
----------------------

- Tests for plone.app.contentlisting all pass and have good coverage.

- alltests run shows nothing unusual.

- Zope fails to start with the following traceback:

    Traceback (most recent call last):
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/Startup/run.py", line 72, in <module>
        run()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/Startup/run.py", line 21, in run
        starter.prepare()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/Startup/__init__.py", line 86, in prepare
        self.startZope()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/Startup/__init__.py", line 259, in startZope
        Zope2.startup()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/__init__.py", line 47, in startup
        _startup()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/App/startup.py", line 118, in startup
        load_zcml()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/App/startup.py", line 52, in load_zcml
        load_site()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/Zope2-2.13.0-py2.6.egg/Zope2/App/zcml.py", line 46, in load_site
        _context = xmlconfig.file(site_zcml)
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 653, in file
        context.execute_actions()
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 606, in execute_actions
        callable(*args, **kw)
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/AccessControl-2.13.3-py2.6-macosx-10.6-x86_64.egg/AccessControl/security.py", line 165, in protectClass
        permission = getUtility(IPermission, name=permission_id)
      File "/Users/cah/src/plone4.1/buildout/plips/eggs/zope.component-3.9.5-py2.6.egg/zope/component/_api.py", line 169, in getUtility
        raise ComponentLookupError(interface, name)
    zope.configuration.config.ConfigurationExecutionError: <class 'zope.component.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'cmf.ModifyPortalContent')
      in:
      File "/Users/cah/src/plone4.1/buildout/src/plone.app.layout/plone/app/layout/viewlets/configure.zcml", line 319.4-325.10
          <browser:viewlet
              name="plone.lockinfo"
              manager=".interfaces.IAboveContent"
              class="plone.locking.browser.info.LockInfoViewlet"
              permission="cmf.ModifyPortalContent"
              for="plone.locking.interfaces.ITTWLockable"
              />

- The code and tests look reasonable.


Conclusion
----------

At this point I cannot effectively review this PLIP, since Zope will
not start.  -1 on merging for now, but I would be happy to look at
this PLIP again if the startup issues can be ironed out.
