Repository: plone.app.widgets
Branch: refs/heads/master
Date: 2015-01-15T18:39:57-03:00
Author: Franco Pellegrini (frapell) <frapell@gmail.com>
Commit: https://github.com/plone/plone.app.widgets/commit/678fa4272811ff3ddcab41ae5ff96c68fc950b27

Fix test case that failed after 1475e889cd582865fe3a23f8c89efe896f6fb541

Files changed:
M plone/app/widgets/tests/test_at.py

diff --git a/plone/app/widgets/tests/test_at.py b/plone/app/widgets/tests/test_at.py
index d8b164b..e5e7594 100644
--- a/plone/app/widgets/tests/test_at.py
+++ b/plone/app/widgets/tests/test_at.py
@@ -553,7 +553,7 @@ def setUp(self):
         self.portal = self.layer['portal']
         self.request = TestRequest(environ={'HTTP_ACCEPT_LANGUAGE': 'en'})
         self.field = Mock()
-        self.field.getAccessor.return_value = lambda: 'fieldvalue'
+        self.field.getRaw.return_value = 'fieldvalue'
         self.field.getName.return_value = 'fieldname'
         self.field.getContentType.return_value = 'text/html'
 


