Repository: plone.app.content


Branch: refs/heads/master
Date: 2015-07-06T01:35:27-05:00
Author: vangheem (vangheem) <vangheem@gmail.com>
Commit: https://github.com/plone/plone.app.content/commit/404d30163d94335c020acbadcb45a61282457b55

give an error when folder does not support ordering

Files changed:
M plone/app/content/browser/contents/__init__.py

diff --git a/plone/app/content/browser/contents/__init__.py b/plone/app/content/browser/contents/__init__.py
index 10f0578..551802f 100644
--- a/plone/app/content/browser/contents/__init__.py
+++ b/plone/app/content/browser/contents/__init__.py
@@ -214,7 +214,10 @@ def __call__(self):
                     self.errors.append(_('Client/server ordering mismatch'))
                     return self.message()
 
-            ordering.moveObjectsByDelta([id], delta)
+            if not hasattr(ordering, 'moveObjectsByDelta'):
+                self.errors.append(_('This folder does not support ordering'))
+            else:
+                ordering.moveObjectsByDelta([id], delta)
         return self.message()
 
 


