Repository: Products.CMFPlone


Branch: refs/heads/4.3.x
Date: 2015-08-24T23:16:35+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/fb32a74d7a2a7a5cc65538cff2f8fab06d09d80b

Rewrite test assertion for sendto script.

I had trouble parsing the previous way it was stated.
The *real* trouble is that the test statement is actually wrong.
We *should* find an error message, but the assertion only passes if this error message is *not* there.
The test passes for the wrong reasons.

Files changed:
M Products/CMFPlone/tests/testSecurityDeclarations.py

diff --git a/Products/CMFPlone/tests/testSecurityDeclarations.py b/Products/CMFPlone/tests/testSecurityDeclarations.py
index 6622a7d..ab4f8d5 100644
--- a/Products/CMFPlone/tests/testSecurityDeclarations.py
+++ b/Products/CMFPlone/tests/testSecurityDeclarations.py
@@ -391,7 +391,7 @@ def test_allowsendto_changed(self):
 
         self.assertFalse(checkPermission(AllowSendto, self.portal))
 
-    def test_sendto_script_failes(self):
+    def test_sendto_script_fails(self):
         # set permission to Manager only
         self.setRoles(['Manager'])
         self.portal.manage_permission(AllowSendto, roles=('Manager',),
@@ -399,11 +399,11 @@ def test_sendto_script_failes(self):
         self.setRoles(['Member'])
         # get sendto script in context of folder
         sendto = self.folder.sendto
-        # should faile with the not allowed msg check if the msg
+        # should fail with the not allowed msg check if the msg
         # contains the string
         msg = sendto()
         errormsg = "You%20are%20not%20allowed%20to%20send%20this%20link"
-        self.assertFalse(str(msg).find(errormsg) != -1, str(msg))
+        self.assertTrue(errormsg in str(msg), str(msg))
 
 
 class TestSkinSecurity(PloneTestCase.PloneTestCase):


Repository: Products.CMFPlone


Branch: refs/heads/4.3.x
Date: 2015-08-24T23:41:40+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/Products.CMFPlone/commit/16dacae3f6d7caf25d3c52f7e2e5f41d3785274c

Reworked sendto permission test.

We must look for the error message in the status message.

Files changed:
M Products/CMFPlone/tests/testSecurityDeclarations.py

diff --git a/Products/CMFPlone/tests/testSecurityDeclarations.py b/Products/CMFPlone/tests/testSecurityDeclarations.py
index ab4f8d5..5b45f42 100644
--- a/Products/CMFPlone/tests/testSecurityDeclarations.py
+++ b/Products/CMFPlone/tests/testSecurityDeclarations.py
@@ -399,11 +399,20 @@ def test_sendto_script_fails(self):
         self.setRoles(['Member'])
         # get sendto script in context of folder
         sendto = self.folder.sendto
-        # should fail with the not allowed msg check if the msg
-        # contains the string
-        msg = sendto()
-        errormsg = "You%20are%20not%20allowed%20to%20send%20this%20link"
-        self.assertTrue(errormsg in str(msg), str(msg))
+        # Set the parameters on the request, so that the validation
+        # script is happy.
+        request = self.folder.REQUEST
+        request['send_to_address'] = 'target@example.org'
+        request['send_from_address'] = 'sender@example.org'
+        from Products.statusmessages.interfaces import IStatusMessage
+        # Clean out any current status messages.
+        IStatusMessage(request).show()
+        # Should fail with the not allowed msg as status message.
+        sendto()
+        status_messages = IStatusMessage(request).show()
+        self.assertEqual(len(status_messages), 1)
+        self.assertEqual(status_messages[0].message,
+                         "You are not allowed to send this link.")
 
 
 class TestSkinSecurity(PloneTestCase.PloneTestCase):


